spring:
  datasource:
    url: jdbc:mysql://18.233.255.172:3306/edusys_01?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: TianShui#2025!
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
server:
  port: 8081
tencent:
  cos:
    bucket-url: https://edu-sys-1365621132.cos.ap-guangzhou.myqcloud.com
